### ISSUE TITLE
被审核检测到了

### ISSUE THREAD

**Issue by zzBelieve** [CoderZhuXH/XHPayKit#11]
<img width="684" alt="qq20190103-092244 2x" src="https://user-images.githubusercontent.com/10309351/50620211-38158e00-0f39-11e9-99f5-fa2e3aa3c346.png">

**Comment by CoderZhuXH** [comment]
一.先检查下项目以下问题
1..删除项目中官方支付SDK(尤其是支付宝SDK)
2..删除项目中所有pay,buy,支付宝,支付字段(苹果会扫描这些字段),若没办法做到删除所有,请一定要删除类名和方法名中这些字段.
二.XHPKit由于用的人过多,为防止被检测到,建议你使用时自行修改XHPKit的类名和方法名.

**Comment by zzBelieve** [comment]
嗯... 确实是项目有 "pay"字段, 来来回回沟通了十几次才上架..  还是不能报侥幸心理,老老实实用内购了.

感谢作者.
