### ISSUE TITLE
如果不用微信SDK,是否可以实现多商户支付?

### ISSUE THREAD

**Issue by sushushu** [CoderZhuXH/XHPayKit#6]
平常我们如果集成微信SDK就要先用AppID注册微信SDK,而且这个AppID一般是写死的,不能动态生成.
用了该框架之后,是否可以动态从服务器取得AppID,不必在客户端写死呢?
```
    // 注册微信SDK
    [WXApi registerApp:WXAPPID];
```

**Comment by CoderZhuXH** [comment]
微信AppID info.plist里面URL types还有一个,没办法做到完全动态从服务器获取
